language: java
jdk:
 - oraclejdk11
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0
deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
  app: currency-converter-api-rafaeln
  on:
    branch: master
  branches:
    only:
      - master
