spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  r2dbc:
    url: r2dbc:h2:mem:///db
    username: sa
    password:

springdoc:
  swagger-ui:
    path: /docs

app:
  config:
    exchange-rates-api:
      url: "http://api.exchangeratesapi.io/v1/latest"
      accessKey:

